---
get_owncloud_bundle_dir: /opt/get-owncloud/bundle
get_owncloud_accept_eula: false
get_owncloud_install_missing_runtime: false
get_owncloud_allow_sudo: false
get_owncloud_contains_generated_secrets: true
get_owncloud_health_timeout: 180
