---
services:
  ocis:
    environment:
      FRONTEND_APP_HANDLER_SECURE_VIEW_APP_ADDR: com.owncloud.api.collaboration.CollaboraOnline
  collaboration:
    image: ${OCIS_IMAGE}
    networks:
      ocis-net: {}
    depends_on:
      ocis:
        condition: service_started
    command: ["collaboration", "server"]
    environment:
      COLLABORATION_GRPC_ADDR: 0.0.0.0:9301
      COLLABORATION_HTTP_ADDR: 0.0.0.0:9300
      MICRO_REGISTRY: nats-js-kv
      MICRO_REGISTRY_ADDRESS: ocis:9233
      COLLABORATION_WOPI_SRC: http://collaboration:9300
      COLLABORATION_APP_NAME: CollaboraOnline
      COLLABORATION_APP_PRODUCT: Collabora
      COLLABORATION_APP_ADDR: ${COLLABORA_EXTERNAL_URL}
      COLLABORATION_APP_ICON: ${COLLABORA_EXTERNAL_URL}/favicon.ico
      COLLABORATION_APP_INSECURE: "false"
      COLLABORATION_CS3API_DATAGATEWAY_INSECURE: "false"
      OCIS_URL: ${OCIS_URL}
    volumes:
      - ${OCIS_CONFIG_DIR}:/etc/ocis${OCIS_BIND_RW_OPTIONS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collaboration.entrypoints=http"
      - "traefik.http.routers.collaboration.rule=Host(`collaboration`)"
      - "traefik.http.services.collaboration.loadbalancer.server.port=9300"
    security_opt:
      - no-new-privileges:true
    restart: always
