---
services:
  ocis:
    environment:
      PROXY_AUTOPROVISION_ACCOUNTS: "true"
      PROXY_ROLE_ASSIGNMENT_DRIVER: oidc
      OCIS_OIDC_ISSUER: ${OCIS_OIDC_ISSUER}
      PROXY_OIDC_REWRITE_WELLKNOWN: "true"
      WEB_OIDC_CLIENT_ID: ${OCIS_OIDC_CLIENT_ID}
      PROXY_USER_OIDC_CLAIM: ${OCIS_OIDC_USER_CLAIM:-preferred_username}
      PROXY_USER_CS3_CLAIM: ${OCIS_OIDC_CS3_CLAIM:-username}
      OCIS_EXCLUDE_RUN_SERVICES: idp,idm
      GRAPH_ASSIGN_DEFAULT_USER_ROLE: "false"
      GRAPH_USERNAME_MATCH: none
      WEB_OIDC_SCOPE: openid profile email
      GRAPH_LDAP_URI: ${LDAP_URI}
      GRAPH_LDAP_BIND_DN: ${LDAP_BIND_DN}
      GRAPH_LDAP_BIND_PASSWORD: ${LDAP_BIND_PASSWORD}
      GRAPH_LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      GRAPH_LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
      GRAPH_LDAP_USER_UID_ATTRIBUTE: ${LDAP_USER_ID_ATTRIBUTE}
      GRAPH_LDAP_USER_NAME_ATTRIBUTE: ${LDAP_USER_NAME_ATTRIBUTE}
      GRAPH_LDAP_GROUP_ID_ATTRIBUTE: ${LDAP_GROUP_ID_ATTRIBUTE}
      GRAPH_LDAP_GROUP_NAME_ATTRIBUTE: ${LDAP_GROUP_NAME_ATTRIBUTE}
      GRAPH_LDAP_SERVER_WRITE_ENABLED: "false"
      GRAPH_LDAP_INSECURE: "false"
      USERS_LDAP_URI: ${LDAP_URI}
      USERS_LDAP_BIND_DN: ${LDAP_BIND_DN}
      USERS_LDAP_BIND_PASSWORD: ${LDAP_BIND_PASSWORD}
      USERS_LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      USERS_LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
      USERS_IDP_URL: ${OCIS_OIDC_ISSUER}
      GROUPS_LDAP_URI: ${LDAP_URI}
      GROUPS_LDAP_BIND_DN: ${LDAP_BIND_DN}
      GROUPS_LDAP_BIND_PASSWORD: ${LDAP_BIND_PASSWORD}
      GROUPS_LDAP_USER_BASE_DN: ${LDAP_USER_BASE_DN}
      GROUPS_LDAP_GROUP_BASE_DN: ${LDAP_GROUP_BASE_DN}
      GROUPS_IDP_URL: ${OCIS_OIDC_ISSUER}
