---
services:
  traefik:
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN}

  ocis:
    image: ${OCIS_IMAGE}
    networks:
      ocis-net: {}
    entrypoint: ["/bin/sh"]
    command: ["-c", "umask 0007; if [ ! -s /etc/ocis/ocis.yaml ]; then ocis init; fi; test -r /etc/ocis/ocis.yaml; exec ocis server"]
    environment:
      OCIS_ADD_RUN_SERVICES: ${START_ADDITIONAL_SERVICES}
      OCIS_URL: ${OCIS_URL}
      OCIS_LOG_LEVEL: ${LOG_LEVEL:-info}
      OCIS_LOG_COLOR: "${LOG_PRETTY:-false}"
      OCIS_LOG_PRETTY: "${LOG_PRETTY:-false}"
      OCIS_INSECURE: "${INSECURE:-false}"
      PROXY_TLS: "false"
      PROXY_ENABLE_BASIC_AUTH: "${PROXY_ENABLE_BASIC_AUTH:-false}"
      GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      IDM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      IDM_CREATE_DEMO_USERS: "${DEMO_USERS:-false}"
      NOTIFICATIONS_SMTP_HOST: ${SMTP_HOST}
      NOTIFICATIONS_SMTP_PORT: ${SMTP_PORT}
      NOTIFICATIONS_SMTP_SENDER: "${SMTP_SENDER:-notifications@localhost.invalid}"
      NOTIFICATIONS_SMTP_USERNAME: ${SMTP_USERNAME}
      NOTIFICATIONS_SMTP_PASSWORD: ${SMTP_PASSWORD}
      NOTIFICATIONS_SMTP_AUTHENTICATION: ${SMTP_AUTHENTICATION}
      NOTIFICATIONS_SMTP_INSECURE: "${SMTP_INSECURE:-false}"
      MICRO_REGISTRY_ADDRESS: 127.0.0.1:9233
      NATS_NATS_HOST: 0.0.0.0
      NATS_NATS_PORT: 9233
      PROXY_CSP_CONFIG_FILE_LOCATION: /etc/ocis/csp.yaml
      COLLABORA_DOMAIN: ${COLLABORA_DOMAIN}
      OCIS_PASSWORD_POLICY_BANNED_PASSWORDS_LIST: banned-password-list.txt
    volumes:
      - ./config/ocis/app-registry.yaml:/etc/ocis/app-registry.yaml${OCIS_BIND_RO_OPTIONS}
      - ./config/ocis/csp.yaml:/etc/ocis/csp.yaml${OCIS_BIND_RO_OPTIONS}
      - ./config/ocis/banned-password-list.txt:/etc/ocis/banned-password-list.txt${OCIS_BIND_RO_OPTIONS}
      - ${OCIS_CONFIG_DIR}:/etc/ocis${OCIS_BIND_RW_OPTIONS}
      - ${OCIS_DATA_DIR}:/var/lib/ocis${OCIS_BIND_RW_OPTIONS}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.entrypoints=https"
      - "traefik.http.routers.ocis.rule=Host(`${OCIS_DOMAIN}`)"
      - "traefik.http.routers.ocis.tls.certresolver=${TRAEFIK_CERT_RESOLVER}"
      - "traefik.http.routers.ocis.service=ocis"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
    security_opt:
      - no-new-privileges:true
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
