---
services:
  ocis:
    environment:
      STORAGE_USERS_DRIVER: s3ng
      STORAGE_SYSTEM_DRIVER: ocis
      STORAGE_USERS_S3NG_ENDPOINT: ${S3NG_ENDPOINT}
      STORAGE_USERS_S3NG_REGION: ${S3NG_REGION}
      STORAGE_USERS_S3NG_ACCESS_KEY: ${S3NG_ACCESS_KEY}
      STORAGE_USERS_S3NG_SECRET_KEY: ${S3NG_SECRET_KEY}
      STORAGE_USERS_S3NG_BUCKET: ${S3NG_BUCKET}
