---
services:
  tika:
    image: docker.io/apache/tika@sha256:21d8052de04e491ccf66e8680ade4da6f3d453a56d59f740b4167e54167219b7
    networks:
      ocis-net: {}
    security_opt:
      - no-new-privileges:true
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
  ocis:
    environment:
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
