---
services:
  tika:
    image: docker.io/apache/tika@sha256:4fd0590937349d7e1a54197d05f6f6f0f7d1d7e1a54197d05f6f6f0f7d1d7e1
    networks:
      ocis-net: {}
    security_opt:
      - no-new-privileges:true
    logging:
      driver: ${LOG_DRIVER:-local}
    restart: always
  ocis:
    environment:
      SEARCH_EXTRACTOR_TYPE: tika
      SEARCH_EXTRACTOR_TIKA_TIKA_URL: http://tika:9998
      FRONTEND_FULL_TEXT_SEARCH_ENABLED: "true"
