---
all:
  children:
    owncloud:
      hosts:
        cloud.example.net:
          ansible_user: deploy
      vars:
        get_owncloud_bundle_dir: /opt/get-owncloud/bundle
        get_owncloud_accept_eula: false
        get_owncloud_install_missing_runtime: true
        get_owncloud_allow_sudo: true
