import { sha256 } from "./crypto.mjs";

const q = (value) => JSON.stringify(String(value));

export function requiredKubernetesTemplatePaths() {
  return ["scripts/install.sh", "scripts/deploy-kubernetes.sh"];
}

function persistence(name, size, storageClassName) {
  const lines = [
    `  ${name}:`,
    "    persistence:",
    "      enabled: true",
    "      accessModes:",
    "        - ReadWriteOnce"
  ];
  if (name === "storageusers") lines.push(`      size: ${q(`${size}Gi`)}`);
  if (storageClassName) lines.push(`      storageClassName: ${q(storageClassName)}`);
  return lines;
}

export function buildHelmValues(profile, sizing) {
  const values = [
    "# Generated by get-owncloud. Chart 0.7.0 is intentionally held at oCIS 7.1.4 under issue #6.",
    "image:",
    "  repository: owncloud/ocis",
    `  tag: ${q("7.1.4")}`,
    "  pullPolicy: IfNotPresent",
    `externalDomain: ${q(profile.networking.domain)}`,
    "logging:",
    "  level: info",
    "  pretty: false",
    "  color: false",
    "insecure:",
    "  oidcIdpInsecure: false",
    "  ocisHttpApiInsecure: false",
    "  ocmInsecure: false",
    "ingress:",
    "  enabled: true",
    `  ingressClassName: ${q(profile.networking.ingressClassName)}`,
    "  tls:",
    `    - secretName: ${q(profile.networking.tlsSecretName)}`,
    "      hosts:",
    `        - ${q(profile.networking.domain)}`,
    "features:",
    "  demoUsers: false",
    "  virusscan:",
    `    enabled: ${Boolean(profile.features.clamav)}`,
    ...(profile.features.clamav ? [
      "    clamav:",
      `      enabled: true`,
      `      image: clamav/clamav@sha256:${profile.features.clamav.imageDigest}`,
      `      storageClassName: ${q(profile.features.clamav.storageClassName)}`,
      `      size: ${q(`${profile.features.clamav.sizeGiB}Gi`)}`,
      `      cpu: ${q(profile.features.clamav.cpu)}`,
      `      memory: ${q(profile.features.clamav.memoryMiB + "Mi")}`
    ] : []),
    "  emailNotifications:",
    `    enabled: ${Boolean(profile.features.notifications && profile.mail?.host)}`,
    "  monitoring:",
    `    enabled: ${profile.features.monitoring === true || profile.features.monitoring?.enabled === true}`,
    ...(profile.office.mode === "collabora" && profile.office.deployment === "bundled" ? [
      "  collabora:",
      "    enabled: true",
      `    domain: ${q(profile.networking.collaboraDomain)}`,
      `    image: collabora/code@sha256:0011be3edac909b390e6f297093bb82f61f9f3ce5476a3bdd4f3ce6b12f74ec3`,
      "    storageClassName:",
      `      data: ${q(profile.storage.storageClassName || "")}`,
      "    persistence:",
      "      data:",
      "        enabled: true",
      "        size: 10Gi",
      "    resources:",
      "      requests:",
      "        cpu: 2",
      "        memory: 4Gi",
      "      limits:",
      "        cpu: 4",
      "        memory: 8Gi"
    ] : []),
    ...(profile.identity.mode === "keycloak" ? [
      "  keycloak:",
      "    enabled: true",
      `    hostname: ${q(profile.networking.domain)}`,
      "    image: docker.io/keycloak/keycloak@sha256:0e3483351197ae1558340473bc54b8f8151842871464090200e58f208c070c30",
      "    database:",
      "      vendor: postgres",
      "      image: docker.io/library/postgres@sha256:9f960731546a19d453f817542225535087991428229813043480184099ce028",
      "    persistence:",
      "      enabled: true",
      "      size: 10Gi",
      `    storageClassName: ${q(profile.storage.storageClassName || "")}`,
      "    resources:",
      "      requests:",
      "        cpu: 1",
      "        memory: 2Gi",
      "      limits:",
      "        cpu: 2",
      "        memory: 4Gi",
      "    secretRefs:",
      "      adminPassword: keycloak-admin-secret",
      "      databasePassword: keycloak-db-secret"
    ] : [])
  ];

  if (profile.features.notifications && profile.mail?.host) {
    values.push(
      "    smtp:",
      `      host: ${q(profile.mail.host)}`,
      `      port: ${Number(profile.mail.port)}`,
      `      sender: ${q(profile.mail.sender)}`,
      ...(profile.mail.senderDisplayName ? [`      senderDisplayName: ${q(profile.mail.senderDisplayName)}`] : []),
      `      authentication: ${q(profile.mail.authentication ?? "none")}`,
      ...(profile.mail.username ? [`      username: ${q(profile.mail.username)}`] : []),
      ...(profile.mail.passwordSecretRef ? [`      passwordSecretRef: ${q(profile.mail.passwordSecretRef)}`] : []),
      `      transportSecurity: ${q(profile.mail.transportSecurity ?? "starttls")}`,
      `      caTrust: ${q(profile.mail.caTrust ?? "system")}`,
      ...(profile.mail.caSecretRef ? [`      caSecretRef: ${q(profile.mail.caSecretRef)}`] : []),
      `      insecure: ${Boolean(profile.mail.insecure)}`
    );
  }

  // Add monitoring configuration
  const monitoring = profile.features.monitoring;
  const monitoringEnabled = monitoring === true || (typeof monitoring === 'object' && monitoring.enabled);
  
  if (monitoringEnabled) {
      if (typeof monitoring === 'object') {
        values.push(
          "    metrics:",
          `      enabled: ${Boolean(monitoring.metrics?.enabled ?? true)}`,
          ...(monitoring.metrics?.endpoint ? [`      endpoint: ${q(monitoring.metrics.endpoint)}`] : []),
          `      authentication: ${Boolean(monitoring.metrics?.authentication ?? false)}`
        );
        
        values.push(
          "    opentelemetry:",
          `      enabled: ${Boolean(monitoring.opentelemetry?.enabled ?? false)}`,
          ...(monitoring.opentelemetry?.endpoint ? [`      endpoint: ${q(monitoring.opentelemetry.endpoint)}`] : []),
          `      protocol: ${q(monitoring.opentelemetry?.protocol ?? "grpc")}`,
          `      tls: ${Boolean(monitoring.opentelemetry?.tls ?? true)}`,
          ...(monitoring.opentelemetry?.caSecretRef ? [`      caSecretRef: ${q(monitoring.opentelemetry.caSecretRef)}`] : [])
        );
      } else {
        // Boolean true case
        values.push(
          "    metrics:",
          "      enabled: true",
          "    opentelemetry:",
          "      enabled: false"
        );
      }
    }

  const externalIdentity = profile.identity.mode === "external-oidc" || profile.identity.mode === "keycloak";
  values.push("  externalUserManagement:", `    enabled: ${externalIdentity}`);
  if (externalIdentity) {
    // For Keycloak, use the Keycloak service URL as the issuer
    const oidcIssuer = profile.identity.mode === "keycloak"
      ? `https://keycloak.${profile.networking.domain}`
      : profile.identity.issuer;
    values.push(
      "    oidc:",
      `      issuerURI: ${q(oidcIssuer)}`,
      `      userIDClaim: ${q(profile.identity.userClaim)}`,
      `      clientId: ${q(profile.identity.clientId ?? "web")}`,
      "      userIDClaimAttributeMapping: username",
      "    ldap:",
      "      writeable: false",
      `      uri: ${q(profile.identity.ldapUri)}`,
      "      certTrusted: true",
      "      insecure: false",
      `      bindDN: ${q(profile.identity.ldapBindDn)}`,
      "      user:",
      `        baseDN: ${q(profile.identity.ldapUserBaseDn)}`,
      "        schema:",
      `          id: ${q(profile.identity.ldapUserIdAttribute)}`,
      `          userName: ${q(profile.identity.ldapUserNameAttribute)}`,
      "      group:",
      `        baseDN: ${q(profile.identity.ldapGroupBaseDn)}`,
      "        schema:",
      `          id: ${q(profile.identity.ldapGroupIdAttribute)}`,
      `          groupName: ${q(profile.identity.ldapGroupNameAttribute)}`
    );
  }

  const collabora = profile.office.mode === "collabora";
  values.push("  appsIntegration:", `    enabled: ${collabora}`);
  if (collabora) {
    const collaboraUrl = profile.office.deployment === "bundled"
      ? `http://collabora.${profile.networking.domain}`
      : profile.office.url;
    values.push(
      "    wopiIntegration:",
      "      officeSuites:",
      `        - name: ${q("Collabora Online")}`,
      `          product: ${q("Collabora")}`,
      "          enabled: true",
      `          uri: ${q(collaboraUrl)}`,
      `          iconURI: ${q(collaboraUrl.replace(/\/$/, "") + "/favicon.ico")}`,
      `          description: ${q("Open office documents with Collabora")}`,
      "          insecure: false",
      "          disableProof: false",
      "          secureViewEnabled: true",
      "          disableChat: false",
      ...(profile.office.deployment === "bundled" ? [
        "          ingress:",
        "            enabled: true",
        `            host: ${q(profile.networking.collaboraDomain)}`,
        "            tls: true"
      ] : [
        "          ingress:",
        "            enabled: false"
      ])
    );
  }

  values.push("secretRefs:");
  if (externalIdentity && profile.identity.mode === "external-oidc") {
    values.push(`  ldapSecretRef: ${q(profile.identity.ldapSecretRef)}`);
  }
  if (profile.identity.mode === "keycloak") {
    values.push(`  keycloakAdminPasswordSecretRef: ${q(profile.identity.keycloakAdminPasswordSecretRef)}`);
    values.push(`  keycloakDatabasePasswordSecretRef: ${q(profile.identity.keycloakDatabasePasswordSecretRef)}`);
  }
  if (profile.storage.mode === "s3ng") values.push(`  s3CredentialsSecretRef: ${q(profile.storage.s3.secretKeyReference)}`);
  if (profile.features.notifications && profile.mail?.username) values.push("  notificationsSmtpSecretRef: owncloud-smtp");
  
  // Add monitoring secret references
  if (profile.features.monitoring && typeof profile.features.monitoring === 'object') {
    const monitoring = profile.features.monitoring;
    if (monitoring.metrics?.authentication && monitoring.metrics.endpoint) {
      values.push("  metricsSecretRef: owncloud-metrics");
    }
    if (monitoring.opentelemetry?.caSecretRef) {
      values.push(`  opentelemetryCaSecretRef: ${q(monitoring.opentelemetry.caSecretRef)}`);
    }
  }

  values.push("services:", "  storageusers:", "    storageBackend:", `      driver: ${q(profile.storage.mode)}`);
  if (profile.storage.mode === "s3ng") {
    values.push(
      "      driverConfig:",
      "        s3ng:",
      `          endpoint: ${q(profile.storage.s3.endpoint)}`,
      `          region: ${q(profile.storage.s3.region)}`,
      `          bucket: ${q(profile.storage.s3.bucket)}`
    );
  }
  values.push("    persistence:", "      enabled: true", "      accessModes:", "        - ReadWriteOnce");
  values.push(`      size: ${q(`${Math.max(10, Math.ceil(sizing.recommended.diskGiB))}Gi`)}`);
  if (profile.storage.storageClassName) values.push(`      storageClassName: ${q(profile.storage.storageClassName)}`);
  for (const name of ["nats", "search", "storagesystem", "thumbnails", "web", "ocm"]) {
    values.push(...persistence(name, 1, profile.storage.storageClassName));
  }
  if (!externalIdentity) {
    values.push(...persistence("idm", 1, profile.storage.storageClassName));
    values.push(...persistence("idp", 1, profile.storage.storageClassName));
  }
  return values.join("\n") + "\n";
}

function application(values) {
  const indented = values.trimEnd().split("\n").map((line) => `        ${line}`).join("\n");
  return `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: owncloud
  source:
    repoURL: https://owncloud.github.io/ocis-charts/
    chart: ocis
    targetRevision: "0.7.0"
    helm:
      releaseName: owncloud
      values: |
${indented}
  destination:
    namespace: owncloud
    server: https://kubernetes.default.svc
`;
}

function project() {
  return `apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: owncloud
  namespace: argocd
spec:
  description: Namespace-scoped ownCloud synchronization boundary
  sourceRepos:
    - https://owncloud.github.io/ocis-charts/
  destinations:
    - namespace: owncloud
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: ServiceMonitor
`;
}

function nfsVerifier() {
  return `apiVersion: batch/v1
kind: Job
metadata:
  name: owncloud-nfs42-verifier
  namespace: owncloud
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: verify
          image: owncloud/ocis:7.1.4
          command: ["/bin/sh", "-ec"]
          args:
            - grep -E ' /verify .*nfs.*(vers|nfsvers)=4\\.2([, ]|$)' /proc/mounts
          volumeMounts:
            - name: data
              mountPath: /verify
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storageusers-data
`;
}

export async function buildKubernetesBundle({ profile, sizing, templates, legal, sources, acceptance }) {
  const values = buildHelmValues(profile, sizing);
  
  // Cache stringified JSON to avoid redundant serialization
  const profileJson = JSON.stringify(profile, null, 2) + "\n";
  const sizingJson = JSON.stringify(sizing, null, 2) + "\n";
  
  const files = {
    "values.yaml": values,
    "install.sh": templates["scripts/install.sh"],
    "deploy.sh": templates["scripts/deploy-kubernetes.sh"],
    "deployment-profile.json": profileJson,
    "sizing-report.json": sizingJson,
    "eula-acknowledgement.json": JSON.stringify({
      accepted: true,
      acceptedAt: acceptance.acceptedAt,
      acceptedBy: acceptance.acceptedBy,
      eulaVersion: legal.version,
      eulaUrl: legal.url,
      eulaSha256: legal.sha256,
      acknowledgedSections: legal.requiredSections,
      runtimeAcceptanceStillRequired: true
    }, null, 2) + "\n"
  };
  if (profile.target.manager === "argocd") {
    files["argocd/application.yaml"] = application(values);
    files["argocd/project.yaml"] = project();
  }
  if (profile.storage.filesystem === "nfs") files["nfs-verifier.yaml"] = nfsVerifier();
  files["deployment.lock.json"] = JSON.stringify({
    formatVersion: 1,
    rendererVersion: "0.2.0",
    chartVersion: "0.7.0",
    ocisVersion: "7.1.4",
    source: sources.sources.ocisCharts,
    eulaSha256: legal.sha256,
    maturity: "community-preview",
    openIssue: 6
  }, null, 2) + "\n";
  files["README.md"] = `# Generated Kubernetes Community Preview\n\nThis bundle is deliberately pinned to chart 0.7.0 / oCIS 7.1.4. Issue #6 remains open. It is not a production claim.\n\n1. Run \`sh install.sh --target kubernetes --manager ${profile.target.manager} --install-missing --allow-sudo\`.\n2. Create the referenced TLS and external-service secrets.\n3. Inspect every file.\n4. Run \`sh deploy.sh --accept-eula${profile.target.manager === "argocd" ? " --argocd" : ""}\`.\n`;
  const hashes = [];
  for (const path of Object.keys(files).sort()) hashes.push(`${await sha256(files[path])}  ${path}`);
  files["manifest.sha256"] = hashes.join("\n") + "\n";
  return files;
}
