import { sha256Text } from "./bundle.mjs";

const q = (value) => JSON.stringify(String(value));

export function requiredKubernetesTemplatePaths() {
  return ["scripts/install.sh", "scripts/deploy-kubernetes.sh"];
}

function persistence(name, size, storageClassName) {
  const lines = [
    `  ${name}:`,
    "    persistence:",
    "      enabled: true",
    "      accessModes:",
    "        - ReadWriteOnce"
  ];
  if (name === "storageusers") lines.push(`      size: ${q(`${size}Gi`)}`);
  if (storageClassName) lines.push(`      storageClassName: ${q(storageClassName)}`);
  return lines;
}

export function buildHelmValues(profile, sizing) {
  const values = [
    "# Generated by get-owncloud. Chart 0.7.0 is intentionally held at oCIS 7.1.4 under issue #6.",
    "image:",
    "  repository: owncloud/ocis",
    `  tag: ${q("7.1.4")}`,
    "  pullPolicy: IfNotPresent",
    `externalDomain: ${q(profile.networking.domain)}`,
    "logging:",
    "  level: info",
    "  pretty: false",
    "  color: false",
    "insecure:",
    "  oidcIdpInsecure: false",
    "  ocisHttpApiInsecure: false",
    "  ocmInsecure: false",
    "ingress:",
    "  enabled: true",
    `  ingressClassName: ${q(profile.networking.ingressClassName)}`,
    "  tls:",
    `    - secretName: ${q(profile.networking.tlsSecretName)}`,
    "      hosts:",
    `        - ${q(profile.networking.domain)}`,
    "features:",
    "  demoUsers: false",
    "  virusscan:",
    "    enabled: false",
    "  emailNotifications:",
    `    enabled: ${Boolean(profile.features.notifications && profile.mail?.host)}`
  ];

  if (profile.features.notifications && profile.mail?.host) {
    values.push(
      "    smtp:",
      `      host: ${q(profile.mail.host)}`,
      `      port: ${Number(profile.mail.port)}`,
      `      sender: ${q(profile.mail.sender)}`,
      `      authentication: ${q(profile.mail.authentication ?? "none")}`,
      `      encryption: ${q(profile.mail.insecure ? "none" : "starttls")}`
    );
  }

  const externalIdentity = profile.identity.mode === "external-oidc";
  values.push("  externalUserManagement:", `    enabled: ${externalIdentity}`);
  if (externalIdentity) {
    values.push(
      "    oidc:",
      `      issuerURI: ${q(profile.identity.issuer)}`,
      `      userIDClaim: ${q(profile.identity.userClaim)}`,
      "      userIDClaimAttributeMapping: username",
      "    ldap:",
      "      writeable: false",
      `      uri: ${q(profile.identity.ldapUri)}`,
      "      certTrusted: true",
      "      insecure: false",
      `      bindDN: ${q(profile.identity.ldapBindDn)}`,
      "      user:",
      `        baseDN: ${q(profile.identity.ldapUserBaseDn)}`,
      "        schema:",
      `          id: ${q(profile.identity.ldapUserIdAttribute)}`,
      `          userName: ${q(profile.identity.ldapUserNameAttribute)}`,
      "      group:",
      `        baseDN: ${q(profile.identity.ldapGroupBaseDn)}`,
      "        schema:",
      `          id: ${q(profile.identity.ldapGroupIdAttribute)}`,
      `          groupName: ${q(profile.identity.ldapGroupNameAttribute)}`
    );
  }

  const collabora = profile.office.mode === "collabora";
  values.push("  appsIntegration:", `    enabled: ${collabora}`);
  if (collabora) {
    values.push(
      "    wopiIntegration:",
      "      officeSuites:",
      `        - name: ${q("Collabora Online")}`,
      `          product: ${q("Collabora")}`,
      "          enabled: true",
      `          uri: ${q(profile.office.url)}`,
      `          iconURI: ${q(`${profile.office.url.replace(/\/$/, "")}/favicon.ico`)}`,
      `          description: ${q("Open office documents with Collabora")}`,
      "          insecure: false",
      "          disableProof: false",
      "          secureViewEnabled: true",
      "          disableChat: false"
    );
  }

  values.push("secretRefs:");
  if (externalIdentity) values.push(`  ldapSecretRef: ${q(profile.identity.ldapSecretRef)}`);
  if (profile.storage.mode === "s3ng") values.push(`  s3CredentialsSecretRef: ${q(profile.storage.s3.secretKeyReference)}`);
  if (profile.features.notifications && profile.mail?.username) values.push("  notificationsSmtpSecretRef: owncloud-smtp");

  values.push("services:", "  storageusers:", "    storageBackend:", `      driver: ${q(profile.storage.mode)}`);
  if (profile.storage.mode === "s3ng") {
    values.push(
      "      driverConfig:",
      "        s3ng:",
      `          endpoint: ${q(profile.storage.s3.endpoint)}`,
      `          region: ${q(profile.storage.s3.region)}`,
      `          bucket: ${q(profile.storage.s3.bucket)}`
    );
  }
  values.push("    persistence:", "      enabled: true", "      accessModes:", "        - ReadWriteOnce");
  values.push(`      size: ${q(`${Math.max(10, Math.ceil(sizing.recommended.diskGiB))}Gi`)}`);
  if (profile.storage.storageClassName) values.push(`      storageClassName: ${q(profile.storage.storageClassName)}`);
  for (const name of ["nats", "search", "storagesystem", "thumbnails", "web", "ocm"]) {
    values.push(...persistence(name, 1, profile.storage.storageClassName));
  }
  if (!externalIdentity) {
    values.push(...persistence("idm", 1, profile.storage.storageClassName));
    values.push(...persistence("idp", 1, profile.storage.storageClassName));
  }
  return values.join("\n") + "\n";
}

function application(values) {
  const indented = values.trimEnd().split("\n").map((line) => `        ${line}`).join("\n");
  return `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: owncloud
  source:
    repoURL: https://owncloud.github.io/ocis-charts/
    chart: ocis
    targetRevision: "0.7.0"
    helm:
      releaseName: owncloud
      values: |
${indented}
  destination:
    namespace: owncloud
    server: https://kubernetes.default.svc
`;
}

function project() {
  return `apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: owncloud
  namespace: argocd
spec:
  description: Namespace-scoped ownCloud synchronization boundary
  sourceRepos:
    - https://owncloud.github.io/ocis-charts/
  destinations:
    - namespace: owncloud
      server: https://kubernetes.default.svc
  clusterResourceWhitelist: []
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: batch
      kind: CronJob
    - group: networking.k8s.io
      kind: Ingress
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: ServiceMonitor
`;
}

function nfsVerifier() {
  return `apiVersion: batch/v1
kind: Job
metadata:
  name: owncloud-nfs42-verifier
  namespace: owncloud
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: verify
          image: owncloud/ocis:7.1.4
          command: ["/bin/sh", "-ec"]
          args:
            - grep -E ' /verify .*nfs.*(vers|nfsvers)=4\\.2([, ]|$)' /proc/mounts
          volumeMounts:
            - name: data
              mountPath: /verify
              readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: storageusers-data
`;
}

export async function buildKubernetesBundle({ profile, sizing, templates, legal, sources, acceptance }) {
  const values = buildHelmValues(profile, sizing);
  const files = {
    "values.yaml": values,
    "install.sh": templates["scripts/install.sh"],
    "deploy.sh": templates["scripts/deploy-kubernetes.sh"],
    "deployment-profile.json": JSON.stringify(profile, null, 2) + "\n",
    "sizing-report.json": JSON.stringify(sizing, null, 2) + "\n",
    "eula-acknowledgement.json": JSON.stringify({
      accepted: true,
      acceptedAt: acceptance.acceptedAt,
      acceptedBy: acceptance.acceptedBy,
      eulaVersion: legal.version,
      eulaUrl: legal.url,
      eulaSha256: legal.sha256,
      acknowledgedSections: legal.requiredSections,
      runtimeAcceptanceStillRequired: true
    }, null, 2) + "\n"
  };
  if (profile.target.manager === "argocd") {
    files["argocd/application.yaml"] = application(values);
    files["argocd/project.yaml"] = project();
  }
  if (profile.storage.filesystem === "nfs") files["nfs-verifier.yaml"] = nfsVerifier();
  files["deployment.lock.json"] = JSON.stringify({
    formatVersion: 1,
    rendererVersion: "0.2.0",
    chartVersion: "0.7.0",
    ocisVersion: "7.1.4",
    source: sources.sources.ocisCharts,
    eulaSha256: legal.sha256,
    maturity: "community-preview",
    openIssue: 6
  }, null, 2) + "\n";
  files["README.md"] = `# Generated Kubernetes Community Preview\n\nThis bundle is deliberately pinned to chart 0.7.0 / oCIS 7.1.4. Issue #6 remains open. It is not a production claim.\n\n1. Run \`sh install.sh --target kubernetes --manager ${profile.target.manager} --install-missing --allow-sudo\`.\n2. Create the referenced TLS and external-service secrets.\n3. Inspect every file.\n4. Run \`sh deploy.sh --accept-eula${profile.target.manager === "argocd" ? " --argocd" : ""}\`.\n`;
  const hashes = [];
  for (const path of Object.keys(files).sort()) hashes.push(`${await sha256Text(files[path])}  ${path}`);
  files["manifest.sha256"] = hashes.join("\n") + "\n";
  return files;
}
