app_registry:
  mimetypes:
    - mime_type: application/vnd.oasis.opendocument.text
      extension: odt
      name: OpenDocument
      description: OpenDocument text document
      default_app: Collabora
      allow_creation: true
    - mime_type: application/vnd.oasis.opendocument.spreadsheet
      extension: ods
      name: OpenSpreadsheet
      description: OpenDocument spreadsheet
      default_app: Collabora
      allow_creation: true
    - mime_type: application/vnd.oasis.opendocument.presentation
      extension: odp
      name: OpenPresentation
      description: OpenDocument presentation
      default_app: Collabora
      allow_creation: true
    - mime_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
      extension: docx
      name: Microsoft Word
      description: Word document
      default_app: Collabora
      allow_creation: true
    - mime_type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
      extension: xlsx
      name: Microsoft Excel
      description: Spreadsheet
      default_app: Collabora
      allow_creation: true
    - mime_type: application/vnd.openxmlformats-officedocument.presentationml.presentation
      extension: pptx
      name: Microsoft PowerPoint
      description: Presentation
      default_app: Collabora
      allow_creation: true
